name: Convox Promote
description: Promote (and optionally verify) a Convox release
author: https://github.com/liamdawson
requirements:
  - convox
  - awk
configuration:
  required:
    - rack
    - app
    - release
  additionalProperties: false
  properties:
    rack:
      type: string
    app:
      type: string
    verify:
      type: boolean
      default: false # TODO: default to verifying, if it'll work with a deploy key
    release:
      oneOf:
        - type: string
        - type: object
          additionalProperties: false
          properties:
            metadata-key:
              type: string
    if-older:
      type: string
      enum:
        - use-rollback
        - fail
